import Head from 'next/head'
import Main from '../components/main'
import Footer from '../components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>WEB.DE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/web.svg" />
      </Head>
      <Main/>
      <Footer/>
    </>
  )
}
